finalTry/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from accounts import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'
urlpatterns = [
    path('committee/login/' , auth_views.login , {'template_name':'registration/committee_login.html'} ,name='committee_login' ) ,
    path('student/login/' , auth_views.login , {'template_name':'registration/student_login.html'} ,name='login' ) ,
    path('logout/' , auth_views.logout , {'next_page': '/'} ,name = 'logout' ) ,
    path('signup/' , views.signup , name = 'signup' ) ,
    path('' , views.index , name = 'index') ,
    path('event/' , views.event , name = 'event') ,
    url(r'^profile/(?P<pk>\d+)/update/$' ,views.StudentProfileUpdate.as_view() , name = 'update_profile' )
]

finalTry/committee/urls.py
from django.conf.urls import url
from django.urls import path
from committee import views
app_name = 'committee'
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('create/event' , views.EventCreateView.as_view() , name = 'create_event') ,
    path('event/list' , views.EventListView.as_view() , name = 'event_list') ,
    path('event/list/today' , views.TodayEventListView.as_view() , name = 'event_list_today') ,
    path('event/list/future' , views.FutureEventListView.as_view() , name = 'event_list_future') ,
]

finalTry/finalTry/urls.py
from django.contrib import admin
from django.urls import path , include
from placement import views as plac

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('accounts.urls')) ,
    path('' , include('committee.urls')) ,
    path('placements/', plac.recruitment_form , name = 'placement') ,
    path('apply/', plac.placement_form , name = 'apply') ,
    path('place-home/', plac.place_index , name = 'place_index') ,
]

finalTry/accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class User(AbstractUser):
    is_student = models.BooleanField('student status', default=False)
    is_committee = models.BooleanField('committee status', default=False)

class StudentProfile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE ,related_name='student_profile')
    linkedin_url = models.URLField(verbose_name="website")
    resume = models.FileField(upload_to="resumes", blank=True)

    def __str__(self):
        return self.user.get_username()

    def get_absolute_url(self):
        return reverse('accounts:index')


class Event(models.Model):
    name = models.CharField(max_length=50 , blank=True)
    start_date = models.DateTimeField(default=None , blank=False , unique=True)
    duration_in_hrs = models.SmallIntegerField(default=0 , blank=True)
    price = models.SmallIntegerField(default=0 , blank=True)
    prize = models.SmallIntegerField(default=0 , blank=True)
    is_approved = models.BooleanField(default=False , blank=True)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('accounts:index')

class CommitteeProfile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE , related_name='committee_profile')
    name = models.CharField(max_length=50 , blank=True)
    events = models.ManyToManyField(Event , related_name='events')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        StudentProfile.objects.get_or_create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.student_profile.save()

finalTry/committee/models.py
from django.db import models
from accounts import models
# Create your models here.

finalTry/placement/models.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django import forms
from finalTry import settings
# Create your models here.
from django.forms import ModelForm

class Applicant(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL , on_delete=models.CASCADE)


class Company(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(blank=True)
    criteria = models.DecimalField(max_digits=4 , decimal_places=2)
    requirement = models.TextField(max_length=260)
    def __str__(self):
        return self.name

class CompanyForm(ModelForm):
    class Meta:
        model = Company
        fields = ['name' , 'email' , 'criteria' , 'requirement']


class PlacementApplyForm(ModelForm):
    company_name = forms.MultipleChoiceField(choices= Company.objects.name  , widget=forms.CheckboxSelectMultiple )
    class Meta:
        model = Applicant
        fields = ['company_name']

finalTry/accounts/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import UserCreationForm

# from  django.contrib.auth import get_user_model
# User = get_user_model()
from accounts.models import User


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1' )

finalTry/committee/forms.py
from django import forms
from django.views.generic import CreateView

from accounts.models import Event

class CreateEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name' , 'start_date' , 'duration_in_hrs' , 'price' , 'prize']

finalTry/accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect


# Create your views here.
from accounts.forms import SignUpForm
from accounts.models import StudentProfile


def index(request):
    return render(request , 'accounts/index.html' , context=None)

def event(request):
    return render(request , 'accounts/events.html' , context=None)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:index')
    else:
        form = SignUpForm()
    return render(request, 'LoginPageStudent.html', {'form': form})

from django.views.generic.edit import UpdateView


class StudentProfileUpdate(UpdateView):
    model = StudentProfile
    fields = ['linkedin_url' , 'resume']
    template_name = 'profile_form.html'

finalTry/committee/views.py
from datetime import date, datetime
from time import timezone

from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView, ListView
from .forms import CreateEventForm
from accounts.models import Event


class EventCreateView(CreateView):
    model = Event
    template_name = 'event_create.html'
    form_class = CreateEventForm

class TodayEventListView(ListView):
    model = Event
    template_name = 'event_list.html'
    def get_queryset(self):
        print(date.today().__str__().split("-")[1])
        return Event.objects.filter( start_date= datetime(2018 , 3 , 24 , 8 , 30))

class FutureEventListView(ListView):
    model = Event
    template_name = 'event_list.html'
    def get_queryset(self):
        return Event.objects.filter( start_date__gt= datetime(2018 , 3 , 24 , 8 , 30) )

class EventListView(ListView):
    model = Event
    template_name = 'event_list.html'

finalTry/placement/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from accounts.models import Event
from placement.models import CompanyForm, Company , PlacementApplyForm

app_name = 'placements'
# def empty_slot():
#     dates = Event.objects.filter('start_date')
#     for a in range(0 , dates.__len__() -1 ):
#         if dates[a].hour == dates[a+1] and dates[a].start_date.hour

def recruitment_form(request):
    if request.method == "POST":
        form = CompanyForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('accounts:index')
    else:
        form = CompanyForm()
    return render(request, 'placements/rec_form.html', {'form': form})

def placement_form(request):
    if request.method == "POST":
        form = PlacementApplyForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('accounts:index')
    else:
        form = PlacementApplyForm()
    return render(request, 'placements/rec_form.html', {'form': form})

def place_index(request):
    return render(request , 'placements/placement_index.html')

finalTry/accounts/templates/HomePage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Event Manager</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="AllTheCSS.css">

</head>
<body id="backg">



  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
{% block content %}
  <div class="container">
    <div class="jumbotron pos1">
  <h1 class="display-4">HOME</h1>
  <p class="lead">"Things can go wrong during events, and very rarely will everything go exactly as we plan."</p>
  <hr class="my-4">
  <p id="lab">Select your Category</p>
    {% if not user.is_authenticated %}
            <button type="button" onclick="window.location.replace('{% url 'accounts:login' %}')" target="_blank" class="btn btn-primary">Login </button><br><br>
        {% endif %}

        {% if user.is_authenticated and user.is_committee %}
            <button type="button" onclick="window.location.replace('{% url 'committee:create_event' %}')" target="_blank" class="btn btn-primary">Event Manager </button><br><br>
        {% endif %}
    <button type="button" onclick="window.location.replace('{% url 'committee:event_list' %}')" target="_blank" class="btn btn-primary">Event Lists </button><br><br>
  </div>

    {% if user.is_authenticated %}
    <div>
        <a href="{% url 'accounts:update_profile' pk=user.student_profile.id %}" >Update Profile</a>
    </div>
        <div>
            <a href="{% url 'accounts:logout' %}" >Logout</a>
        </div>
    {% else %}
        <div class="container">
        <a href="{% url 'accounts:signup' %}">SignUp</a>
        </div>
    {% endif %}
  </div>
{% endblock %}
</body>
</html>

finalTry/accounts/templates/LoginPageStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Login Form</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="AllTheCSS.css">
<link href='https://fonts.googleapis.com/css?family=Fasthand' rel='stylesheet'>

</head>

<body id="backg">
<div class="login-form container">
    <form method="POST" class="container" enctype="multipart/form-data" >
    <div class="col">
        {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn-success ml-5 mr-0" value="Submit" />
    </div>
    </form>
</div>
</body>
</html>

finalTry/accounts/templates/accounts/All The HTML FILES/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Event Manager</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="AllTheCSS.css">
    <style type="text/css">
    #pos7{
        position: relative;
        left : 192px;
        margin-right: 30px;
    }
    #backg{
            background-image: url({% static "images/bg.png" %});
        }
        .pos6{
            width : 800px;
            height : 400px;
            border-radius: 30px;
            position: relative;
            left : 150px;
            top : 100px;
        }
    </style>
</head>
<body id="backg">
    {% block content %}
  <div class="container">
    <div class="jumbotron pos1">
  <h1 class="display-4">HOME</h1>
  <p class="lead">"Things can go wrong during events, and very rarely will everything go exactly as we plan."</p>
  <hr class="my-4">
  <p id="lab">Select your Category</p>
    {% if not user.is_authenticated %}
            <button type="button" onclick="window.location.replace('{% url 'accounts:login' %}')" target="_blank" class="btn btn-primary">Login </button><br><br>
        {% endif %}

        {% if user.is_authenticated and user.is_committee %}
            <button type="button" onclick="window.location.replace('{% url 'committee:create_event' %}')" target="_blank" class="btn btn-primary">Event Manager </button><br><br>
        {% endif %}
    <button type="button" onclick="window.location.replace('{% url 'committee:event_list' %}')" target="_blank" class="btn btn-primary">Event Lists </button><br><br>
  </div>

    {% if user.is_authenticated %}
    <div>
        <a href="{% url 'accounts:update_profile' pk=user.student_profile.id %}" >Update Profile</a>
    </div>
        <div>
            <a href="{% url 'accounts:logout' %}" >Logout</a>
        </div>
    {% else %}
        <div class="container">
        <a href="{% url 'accounts:signup' %}">SignUp</a>
        </div>
    {% endif %}
  </div>
{% endblock %}


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

finalTry/accounts/templates/accounts/All The HTML FILES/index.html
{% extends 'accounts/All The HTML FILES/base.html' %}
{% block content %}
    <div class="container mt-5 mb-5" id="backg">
        <div class="col">
            <div class="row">
                <div class="jumbotron pos6">
                    <p>Enter your Category</p>
                    <br><hr><br>
                    <button id="pos7"type="button" class="btn btn-primary" onclick="location.href={% url 'accounts:event' %}">Events</button>
                    <button id="pos7"type="button" class="btn btn-primary" onclick="Location.href = {% url 'placement' %}">Placement</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

finalTry/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Event Manager</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="AllTheCSS.css">
    <style type="text/css">
    #pos7{
         padding: 10px 20px;
    font-size: 60px;
        margin-right: 20px;
    border-radius: 10px;
        margin : auto auto ;
    }
    #backg{
            background-image: url({% static "images/bg.png" %});
        }
        .pos6{
            width : 800px;
            height : 400px;
            border-radius: 30px;
            position: relative;
            left : 150px;
            top : 100px;
        }
        .sty{
            height : 1000px;
        }
        #texts{
            font-size: 60px;
            color : green;
            position : relative;
            left : 400px;
        }
    </style>
</head>
<body>
{#    {% if user.is_authenticated %}#}
{#    <div>#}
{#        <a href="{% url 'accounts:update_profile' pk=user.student_profile.id %}" >Update Profile</a>#}
{#    </div>#}
{#        <div>#}
{#            <a href="{% url 'accounts:logout' %}" >Logout</a>#}
{#        </div>#}
{#    {% else %}#}
{#        <div class="container">#}
{#        <a href="{% url 'accounts:signup' %}">SignUp</a>#}
{#        </div>#}
{#    {% endif %}#}
{#  </div>#}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark m-auto">
  <a class="navbar-brand" href="#">EventsOrganiZer</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <ul class="nav navbar-nav ml-auto mr-2">
          {% if user.is_authenticated %}
              <li>
                <a class="nav-link disabled" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
              <li>
              <a href="{% url 'accounts:update_profile' pk=user.student_profile.id %}" >Update Profile</a>
              </li>
              <li>
                    <a style="color: white" class="nav-link">Welcome {{ user.username }}</a>
                </li>
          {% else %}
              <li>
              <a class="nav-link btn-outline-dark" href="{% url 'accounts:login' %}">Login</a>
              </li>
              <li>
              <a class="nav-link btn-outline-dark" href="{% url 'accounts:signup' %}">SignUp</a>
              </li>
          {% endif %}
      </ul>
    </ul>
  </div>
</nav>
    {% block content %}
  <div class="container">
    <div class="jumbotron pos1">
  <h1 class="display-4">HOME</h1>
  <p class="lead">"Things can go wrong during events, and very rarely will everything go exactly as we plan."</p>
  <hr class="my-4">
  <p id="lab">Select your Category</p>
    {% if not user.is_authenticated %}
            <button type="button" onclick="window.location.replace('{% url 'accounts:login' %}')" target="_blank" class="btn btn-primary">Login </button><br><br>
        {% endif %}

        {% if user.is_authenticated and user.is_committee %}
            <button type="button" onclick="window.location.replace('{% url 'committee:create_event' %}')" target="_blank" class="btn btn-primary">Event Manager </button><br><br>
        {% endif %}
    <button type="button" onclick="window.location.replace('{% url 'committee:event_list' %}')" target="_blank" class="btn btn-primary">Event Lists </button><br><br>
  </div>


{% endblock %}


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

finalTry/accounts/templates/accounts/events.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container mt-5 mb-5">
        <div class="col">
            <div class="row">
                        <div class="jumbotron">
                            <div class="container">
            <div class="jumbotron pos1">
          <h1 class="display-4">HOME</h1>
          <p class="lead">"Things can go wrong during events, and very rarely will everything go exactly as we plan."</p>
          <hr class="my-4">
          <p id="lab">Select your Category</p>
            {% if not user.is_authenticated %}
                    <button type="button" onclick="window.location.replace('{% url 'accounts:login' %}')" target="_blank" class="btn btn-primary">Login </button><br><br>
                {% endif %}

                {% if user.is_authenticated and user.is_committee %}
                    <button type="button" onclick="window.location.replace('{% url 'committee:create_event' %}')" target="_blank" class="btn btn-primary">Event Manager </button><br><br>
                {% endif %}
            <button type="button" onclick="window.location.replace('{% url 'committee:event_list' %}')" target="_blank" class="btn btn-primary">Event Lists </button><br><br>
          </div>

            {% if user.is_authenticated %}
            <div>
                <a href="{% url 'accounts:update_profile' pk=user.student_profile.id %}" >Update Profile</a>
            </div>
                <div>
                    <a href="{% url 'accounts:logout' %}" >Logout</a>
                </div>
            {% else %}
                <div class="container">
                <a href="{% url 'accounts:signup' %}">SignUp</a>
                </div>
            {% endif %}
          </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

finalTry/accounts/templates/accounts/index.html
{% extends 'accounts//base.html' %}
{% block content %}

            <div class="container-fluid">
                <div class="jumbotron sty" >
                    <p id="texts" class="ml-auto mr-auto pos7"> Welcome to Event Manager</p>
                    <br><hr><br>
                    <button id="pos7"type="button" class="btn btn-primary" onclick="location.href={% url 'accounts:event' %}">Events</button>
                    <button id="pos7"type="button" class="btn btn-primary" onclick="location.href={% url 'place_index' %}">Placement</button>
                </div>
            </div>


{% endblock %}

finalTry/accounts/templates/accounts/template.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="container mt-5 mb-5">
        <div class="col">
            <div class="row">
                <div class="jumbotron">


                </div>
            </div>
        </div>
    </div>
{% endblock %}

finalTry/accounts/templates/create&Manage.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Event Manager</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" type="text/css" href="AllTheCSS.css">

</head>
<body id="backg">

  <div class="container ">
  <div class="jumbotron pos1">
  <h1 class="display-4">Create OR Manage</h1>
  <p class="lead">"Things can go wrong during events, and very rarely will everything go exactly as we plan."</p>
  <hr class="my-4">
  <p id="lab">    Choose an option</p>
  <button type="button" onclick="window.open('Create.html')" class="btn btn-primary">Create </button><br><br>
  <button type="button" onclick="window.open('Manage.html')" target=""class="btn btn-primary">Manage</button>
  </div>

</div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</body>
</html>

finalTry/accounts/templates/profile_form.html
{% extends 'HomePage.html' %}
{% block content %}

    <div class="container" style = "position : relative; left : 400px; top : 200px;">
    <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
    </form>
    </div>
{% endblock %}

finalTry/committee/templates/ALL HTML FILES/event_list.html
{% extends 'HomePage.html' %}
{% block content %}
    <div class="container">

    </div>
    <div class="Jumbotron pos8">

        <h1>List of Events</h1>

        {% for event in event_list %}
            <p> {{ event.name }} on <span class="space">{{ event.date }}</span><span class="space">{{ event.price }}</span></p>
    {% endfor %}
    </div>
    </div>
{% endblock %}

finalTry/committee/templates/event_list.html
{% extends 'HomePage.html' %}
{% block content %}
    <div class="container">
    <div class="Jumbotron pos8">

        <h1>List of Events</h1>

        {% for event in event_list %}
            <p> {{ event.name }} on <span class="space">{{ event.start_date }}</span><span class="space">  {{ event.price }}rs</span></p>
        {% endfor %}
    <span><a  class="container" href="{% url 'committee:event_list_today' %}">Ongoing Events</a> </span>
    <span><a class="container" href="{% url 'committee:event_list_future' %}">Upcoming Events</a> </span>
    </div>
    </div>
    </div>
{% endblock %}